Support `AutoDeploymentsEnabled`
awslabs/amazon-app-runner-deploy pull request #26
Opened 2022-12-13 14:29 UTC by Suyama-Daichi

*Issue #, if available:*
Support `AutoDeploymentsEnabled`
*Description of changes:*
Support `AutoDeploymentsEnabled`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-14 00:21 UTC, DmitryGulin requested changes
kindly ask you to make sure that there is no unused code introduced.

2022-12-14 00:21 UTC, DmitryGulin commented on src/action-configuration.ts
> +    autoDeploymentsEnabled: boolean
what is the reason for having a copy of that configuration parameter at the root level, although the only one defined on `ICodeConfiguration` interface is being used by the rest of the code?

2022-12-14 00:21 UTC, DmitryGulin commented on src/action-configuration.ts
> +        autoDeploymentsEnabled
unused

2022-12-14 00:21 UTC, DmitryGulin commented on src/action-configuration.ts
> +    const autoDeploymentsEnabled = getInputBool('auto-deployments-enabled', true)
unused

2023-01-19 20:23 UTC, brandonrobertz commented
Is it just a matter of removing those two lines that is blocking this? Being able to disable the auto deploy upon commit functionality here would be super useful.

2025-02-20 12:30 UTC, mmartinez commented
It's embarrassing to see that its taking 3+ years to deal with such a simple thing. I think AWS has forgotten about the customers.

2026-06-10 14:41 UTC, closed without merging