Support tags
awslabs/amazon-app-runner-deploy pull request #28
Opened 2023-01-07 06:10 UTC by yyamanoi1222

*Issue #21

*Description of changes:*
Add tags input

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-18 21:40 UTC, DmitryGulin commented
Thank you very much for your PR!

I'd recommend simplifying the tag defintion format.

The current approach expects action authors to use an array of [Tag](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apprunner/interfaces/tag.html) compatible objects, so that the defintion would look like this:

``` json
[{ "Key": "first_tag", "The first tag value": "Tag Value" }, { "Key": "second_tag", "Value": "The second tag value" }]
```

The current approach is too verbose and unnecessary exposes internal dependency on AWS SDK API as a public contract.
That said, I'd suggest using a simplified version to make action defintion easier for action authors to create, understand, and support:

``` json
{ "first_tag": "The first tag value", "second_tag": "The second tag value" }
```

2023-01-18 21:43 UTC, DmitryGulin requested changes
see my comment in the Conversation thread

2023-01-19 10:55 UTC, yyamanoi1222 commented
@DmitryGulin Thank you for your feedbacks!
I changed the format

2023-02-08 17:10 UTC, DmitryGulin approved these changes

2023-02-08 17:11 UTC, merged