Allow using float value in memory and cpu config
awslabs/amazon-app-runner-deploy pull request #42
Opened 2023-04-27 23:08 UTC by yyamanoi1222

*Issue #39, if available:*

*Description of changes:*
change parse logic to `Number` from `parseInt`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-28 14:25 UTC, DmitryGulin requested changes
I don't think it makes sense to allow float numbers for `port` and `wait-for-service-stability-seconds` parameters.
Moreover, adding additional tests to validate that 0.5 and 0.25 do not result in rounding to an integer would be great too.

2023-04-29 07:07 UTC, yyamanoi1222 commented
@DmitryGulin thank you for you review. I gonna split a method into parseInt and parseFloat.

2023-04-29 07:58 UTC, yyamanoi1222 commented
@DmitryGulin I added a argument for parsing only int. Could you review it again?

2023-06-14 15:02 UTC, DmitryGulin approved these changes

2023-06-14 15:02 UTC, merged